### ISSUE TITLE
Can I reproduce your module _custom_arrows.asy?

### ISSUE THREAD

**Issue by justonly011298** [ryanmaguire/Mathematics-and-Physics#2]
I was wonderring if I could reproduce your module _custom_arrows.asy to do my personal things?

**Comment by ryanmaguire** [comment]
Hello,

I'm not sure what you mean by reproduce it. If you mean use it, then yes. All of the code is released under the GPL3 license which is quite permissive. Please report any bugs back here should they pop up.

-Ryan
