### ISSUE TITLE
Link on github pages is wrong

### ISSUE THREAD

**Issue by neozhaoliang** [ryanmaguire/Mathematics-and-Physics#3]
Hi: Thanks for these beautiful illustrations.

The link on github pages is wrong, I assume it should jump to this source code repository, not the gallery page itself?

**Comment by ryanmaguire** [comment]
Hello,

Sorry, it's been a while since I've worked on this.
Currently working on a vector graphics library in C so I can continue with this project.

Could you clarify what you're asking?

**Comment by neozhaoliang** [comment]
![2021-06-28 13-25-26屏幕截图](https://user-images.githubusercontent.com/23307174/123584646-53b13500-d814-11eb-870b-163a5d52c8d4.png)

I mean, the button above does not lead to the source code: https://ryanmaguire.github.io/asymptote/

A vector graphics library in C sounds interesting. Would it support TeX and 3d graphics?

**Comment by ryanmaguire** [comment]
Ohhh! Thank you for bringing that to my attention.
I have been greatly reorganizing this repo and trying to clean up the asymptote code and tikz code.
I'll fix that once the reorganization is complete.

Thanks!

**Comment by neozhaoliang** [comment]
BTW, if you are interested in drawing hyperbolic/euclidean figures, maybe you can have a look at my project  here:

https://github.com/neozhaoliang/pywonderland/blob/master/src/uniform-tilings

Also the way you draw fractals in python can be made much faster.

**Comment by ryanmaguire** [comment]
Hi again,

Sorry for the delayed response, I need to learn to check the issues section more often.
I am actually trying to algorithmically produce hyperbolic tilings. Specifically the (8,3) tiling to represent embeddings of graphs on genus 2 surfaces. Unfortunately the link you left gave me a 404 error. 

In my email there was a question about my C library that seems to have disappeared. It does not (unfortunately) support latex embeddings, but does support 3D drawings. 2D images are rendered as SVG, which I could not for the life of me figure out how to embed LaTeX into.

The reason I started it was to draw very large random walks on 2D manifolds. Particularly a random walk with 500,000 steps on a torus. Asymptote unfortunately crashes if you try to draw that many elements.
Here's the preliminary code to make such a figure.
https://github.com/ryanmaguire/libtmpl/blob/master/extras/random_walk/tmpl_random_walk_on_a_torus_to_svg.c

**Comment by neozhaoliang** [comment]
Oh my mistake. The code for that project has been moved to the released code here:
https://github.com/neozhaoliang/pywonderland/releases/tag/0.1.0

The documentation is online:  
https://pywonderland.com/uniform-tilings/
